/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Dao.DAOAgenciaDeViajes;
import Dao.DAOClientes;
import Exceptions.DAOException;
import ObjetosGUI.AgenciaDeViajes;
import ObjetosGUI.Clientes;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cocob
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Inicio de Sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIniciarSesion.setIcon(new javax.swing.ImageIcon("/Users/alejandrobel/Desktop/ISW/BDA_avanzada/Proyecto-3/Proyecto_3/src/main/resources/Iconos/costumer-icon.png")); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIniciarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        if (txtUsuario.getText().equals("") || txtContra.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos por favor.");
            return;
        }
        if (revisarUsuario() == 1) {
            frmReservacionCliente frame = new frmReservacionCliente();
            frame.setVisible(true);

            this.setVisible(false);
            this.dispose();
        } else if (revisarUsuario() == -1) {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado.");
        } else if (revisarUsuario() == 0) {
            JOptionPane.showMessageDialog(null, "Contraseña inválida, intente de nuevo.");
        } else if (revisarUsuario() == 2) {
            frmReservacionAgencia frame = new frmReservacionAgencia();
            frame.setVisible(true);

            this.setVisible(false);
            this.dispose();
        } 

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private int revisarUsuario() {
        DAOClientes dao = new DAOClientes();
        DAOAgenciaDeViajes daoA = new DAOAgenciaDeViajes();
        try {
            ArrayList<Clientes> clientes = dao.consultar();
            ArrayList<AgenciaDeViajes> agencia = daoA.consultar();
            
            String usuario = txtUsuario.getText();
            String contra = String.valueOf(txtContra.getPassword());
            
            for (Clientes cliente : clientes) {
                if (cliente.getUsuario().equals(txtUsuario.getText()) && cliente.getContraseña().equals(contra)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido " + cliente.getUsuario() + ".");
                    return 1;
                }

                if (cliente.getUsuario().equals(usuario)) {
                    return 0;
                }
        }
            for (AgenciaDeViajes agenciaDeV : agencia) {
                if (agenciaDeV.getUsuario().equals(txtUsuario.getText()) && agenciaDeV.getContraseña().equals(contra)) {
                    JOptionPane.showMessageDialog(null, "Bienvenido " + agenciaDeV.getUsuario() + ".");
                    return 2;
                }
                if (agenciaDeV.getUsuario().equals(usuario)) {
                    return 0;
                }

            }

    }catch (DAOException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, intente de nuevo.");
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e);
        }
        return -1;
    }
    

//    private int revisarUsuario() {
//        DAOClientes dao = new DAOClientes();
//        ArrayList<Clientes> clientes = null;
//
//        try {
//            clientes = dao.consultar();
//        } catch (DAOException e) {
//            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, intente de nuevo.");
//            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e);
//        }
//
//        if (clientes.size() == 0) {
//            return -1;
//        }
//
//        String contra = String.valueOf(txtContra.getPassword());
//
//        for (Clientes cliente : clientes) {
//            if (cliente.getUsuario().equals(txtUsuario.getText()) && cliente.getContraseña().equals(contra)) {
//                JOptionPane.showMessageDialog(null, "Bienvenido " + cliente.getUsuario() + ".");
//                return 1;
//            }
//
//            if (cliente.getUsuario().equals(txtUsuario.getText())) {
//                return 0;
//            }
//        }
//        return -1;
//    }
//
//    private int revisarUsuario2() {
//        DAOAgenciaDeViajes daoA = new DAOAgenciaDeViajes();
//        ArrayList<AgenciaDeViajes> agencia = null;
//
//        try {
//            agencia = daoA.consultar();
//        } catch (DAOException e) {
//            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, intente de nuevo.");
//            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e);
//        }
//
//        if (agencia.size() == 0) {
//            return -1;
//        }
//
//        String contra = String.valueOf(txtContra.getPassword());
//
//        for (AgenciaDeViajes agenciaDeV : agencia) {
//            if (agenciaDeV.getUsuario().equals(txtUsuario.getText()) && agenciaDeV.getContraseña().equals(contra)) {
//                JOptionPane.showMessageDialog(null, "Bienvenido " + agenciaDeV.getUsuario() + ".");
//                return 1;
//            }
//            if (agenciaDeV.getUsuario().equals(txtUsuario.getText())) {
//                return 0;
//            }
//
//        }
//        return -1;
//    }
}
